---

root: true

plugins:
  - functional

extends:
  - airbnb
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"


parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest

env:
  browser: true
  node: true
  jest: true
  es2022: true

settings:
  import/resolver:
    node: true
    webpack: true
    alias: 
      map: 
        - - src
          - ./src
        - - components
          - ./src/components
        - - screens
          - ./src/screens
        - - utils
          - ./src/utils
        - - store
          - ./src/store
    

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  no-shadow: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function 
